# Site settings
title: CarganCode
email: tim@cargancode.io
description: "This is a website, yes I know. This is my website, the one and only Tim Cargan! on it you will find awesome pics and code and what ever else I feel like putting on it."
baseurl: ""
url: "http://cargancode.io"
twitter_username: timcargan
github_username:  timcargan

# Build settings
markdown: kramdown
permalink: pretty
pygments: true

paginate: 10
paginate_path: "blog/page:num"
excerpt_separator: <!--more-->
sass:
    sass_dir: css/
    