# Site settings
title: Cargan Code
email: tim@cargancode.com
description: "This is a website, yes I know. This is my website, the one and only Tim Cargan! on it you will find awesome pics and code and what ever else I feel like putting on it. Copyright © 2014 CarganCode Inc. & all its awesomeness"
baseurl: ""
url: "http://cargancode.com"
twitter_username: timcargan
github_username:  timcargan

# Build settings
markdown: kramdown
permalink: pretty
pygments: true
highlighter: true

sass:
    sass_dir: css/
    